name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  run-tests:
    name: Run tests to avoid a broken release
    uses: BIMAU/transiflow/.github/workflows/ci.yml@master

  build:
    name: Build packages
    runs-on: ubuntu-latest
    needs:
      - run-tests

    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '>=3.8,<4'

    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Build a source package and a wheel
      run: python -m build .

    - name: Upload packages as artifact
      uses: actions/upload-artifact@v4
      with:
        name: packages-for-pypi
        path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs:
      - build

    environment:
      name: pypi
      url: https://pypi.org/p/transiflow

    permissions:
      id-token: write

    steps:
      - name: Download artifact with packages
        uses: actions/download-artifact@v4
        with:
          name: packages-for-pypi
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
